create database Ac1
go

use Ac1
go

create table Produtos (
ID INT PRIMARY KEY,
Nome VARCHAR(50) NOT NULL,
Preço FLOAT NOT NULL,
Estoque INT,
categoria VARCHAR(50)
)drop table Produtos/* Inserir 10 produtos na tabela*/insert into Produtos(ID, Nome, Preço, Estoque, categoria)values(1, 'Caixa_de_Camisinha', 12, 300, 'Corporal');insert into Produtos(ID, Nome, Preço, Estoque, categoria)values(2, 'Oleo_de_motor', 20, 600, 'Carros');insert into Produtos(ID, Nome, Preço, Estoque, categoria)values(3, 'Caderno_Para_Desenho', 30, 1000, 'Escolar');insert into Produtos(ID, Nome, Preço, Estoque, categoria)values(4, 'Teclado', 3000, 400, 'Eletrônico');insert into Produtos(ID, Nome, Preço, Estoque, categoria)values(5, 'Oleo_Corporal', 130, 257, 'Corporal');insert into Produtos(ID, Nome, Preço, Estoque, categoria)values(6, 'Iphone_15', 10000, 645, 'Eletrônico');insert into Produtos(ID, Nome, Preço, Estoque, categoria)values(7, 'Mouse', 5000, 1233, 'Eletrônico');insert into Produtos(ID, Nome, Preço, Estoque, categoria)values(8, 'Monitor', 9000, 1356, 'Eletrônico');insert into Produtos(ID, Nome, Preço, Estoque, categoria)values(9, 'Tablet', 2500, 131, 'Eletrônico');insert into Produtos(ID, Nome, Preço, Estoque, categoria)values(10, 'Action_figure_Anya', 320, 900, 'Decoração');/*Selecionar todos os campos e todos os produtos*/select ID,Nome,Preço,Estoque,categoria from Produtos;/*Selecionar o nome e o preço de todos os produtos em ordem alfabética*/select Nome,Preço from Produtosorder by Nome;/*Selecionar todos os produtos com preço maior que R$100,00*/select ID,Nome,Preço,Estoque,categoria from produtoswhere Preço>=100/*Selecionar todos os produtos com estoque disponível, em ordem decrescente de preço*/select ID,Nome,Preço,Estoque,categoria from produtoswhere Estoque>=1order by Preço desc/*Escrever o preço do produto de maior valor*/select max(Preço) from produtos/*- Escrever o preço do produto de menor valor*/select min(Preço) from produtos/*- Selecionar todos os produtos que custem entre R$500,00 e R$1000,00 em ordem
crescente de preço*/select ID,Nome,Preço,Estoque,categoria from produtoswhere Preço between 500 and 1000order by Preço/*Selecionar todos os produtos da categoria ELETRÔNICO cujo preço seja superior a
R$350,00*/select ID,Nome,Preço,Estoque,categoria from produtoswhere categoria='Eletrônico' and Preço>=350/*Exiba o valor total de todos os produtos em estoque*/select sum(Estoque) from produtos/*Mostre o valor médio de todos os produtos em estoque, que custe até R$600,00 e que
são da categoria PERECÍVEL*/select avg(Estoque) from produtoswhere Preço>=600 and categoria='Perecível'/*- Exiba todos os produtos cujo nome comece com SMARTPHONE*/select ID,Nome,Preço,Estoque,categoria from produtoswhere Nome='Smartphone%'/*Exiba o menor preço de produto com estoque disponível*/select min(Preço) from produtoswhere Estoque>=1/*Exiba todos os produtos cujo nome termine com EM PÓ, em ordem decrescente de preço,
que estão com estoque disponíveis*/select ID,Nome,Preço,Estoque,categoria from produtoswhere Nome='%Em_Pó' and Estoque>=1order by Preço desc/*Exiba todos os produtos sem estoque em ordem alfabética*/select ID,Nome,Preço,Estoque,categoria from produtoswhere Estoque<1order by Nome/*Exiba a contagem de produtos sem estoque*/select count(Estoque) from produtoswhere Estoque<1/*Exiba a contagem de produtos com estoque da categoria LIMPEZA*/select count(Estoque) from produtoswhere categoria='Limpeza'/*Exiba todos os produtos com valor inferior a R$50,00*/select ID,Nome,Preço,Estoque,categoria from produtoswhere Preço<50/*Exiba todos os produtos cujo nome contenha a palavra PROMOÇÃO*/select ID,Nome,Preço,Estoque,categoria from produtoswhere Nome='%Promoção%'