create database atividade
go

use atividade
go

create table veiculos(
Placa varchar(7) primary key not null,
Marca varchar(20) not null,
Modelo varchar(20) not null,
Cor varchar(20) not null,
Ano int not null,
Valor_de_compra float not null,
Valor_de_Venda float not null)goinsert into veiculos(Placa, Marca, Modelo, Cor, Ano, Valor_de_compra, Valor_de_venda)values('DAB5832','VOLKS','Golf','azul',2018,180000,40000)insert into veiculos(Placa, Marca, Modelo, Cor, Ano, Valor_de_compra, Valor_de_venda)values('NQV8626','VOLKS','Tera','vermelho0',2022,80000, 190000)insert into veiculos(Placa, Marca, Modelo, Cor, Ano, Valor_de_compra, Valor_de_venda)values('DBA5908','VOLKS','jetta','roxo',1970,90000,135000)insert into veiculos(Placa, Marca, Modelo, Cor, Ano, Valor_de_compra, Valor_de_venda)values('FRB0344','CHEVROLET','Cruze','Preto',2018,180000,40000)insert into veiculos(Placa, Marca, Modelo, Cor, Ano, Valor_de_compra, Valor_de_venda)values('XDR0298','CHEVROLET','Celta','Branco',2013,160000,205000)insert into veiculos(Placa, Marca, Modelo, Cor, Ano, Valor_de_compra, Valor_de_venda)values('APO7820','CHEVROLET','Onix','Prata',1890,200000,120000)insert into veiculos(Placa, Marca, Modelo, Cor, Ano, Valor_de_compra, Valor_de_venda)values('POG3654','FORD','Ranger','Ferro',1950,200000,50000)insert into veiculos(Placa, Marca, Modelo, Cor, Ano, Valor_de_compra, Valor_de_venda)values('WGT2768','FORD','Focus','Gelo',2004,185000,65000)insert into veiculos(Placa, Marca, Modelo, Cor, Ano, Valor_de_compra, Valor_de_venda)values('LNY0543','FORD','Ka','Mofo',2000,20050,57000)insert into veiculos(Placa, Marca, Modelo, Cor, Ano, Valor_de_compra, Valor_de_venda)values('BDR9503','FIAT','Palio','marrom',1980,90000,140000)insert into veiculos(Placa, Marca, Modelo, Cor, Ano, Valor_de_compra, Valor_de_venda)values('WGT1068','FORD','adr','a',2022,185000,65000)insert into veiculos(Placa, Marca, Modelo, Cor, Ano, Valor_de_compra, Valor_de_venda)values('WGT2068','FORD','adr','a',2025,185000,65000)/*1 Selecione todos os veículos*/select Placa,Marca,Modelo,Cor,Ano,Valor_de_compra,Valor_de_Venda from veiculos/*2*/select Placa,Marca,Modelo,Cor,Ano,Valor_de_compra,Valor_de_Venda from veiculosorder by Modelo/*3*/select Placa,Marca,Modelo,Cor,Ano,Valor_de_compra,Valor_de_Venda from veiculosorder by Marca/*4*/select Placa,Marca,Modelo,Cor,Ano,Valor_de_compra,Valor_de_Venda from veiculosorder by Valor_de_Venda desc/*5*/select Placa,Marca,Modelo,Cor,Ano,Valor_de_compra,Valor_de_Venda from veiculosorder by Ano/*6*/select Placa,Marca,Modelo,Cor,Ano,Valor_de_compra,Valor_de_Venda from veiculosWhere Placa like 'DAB%'/*7*/select Placa,Marca,Modelo,Cor,Ano,Valor_de_compra,Valor_de_Venda from veiculosWhere Marca like 'CHEVROLET'/*8*/select count(Placa) from veiculos/*9*/select Placa,Marca,Modelo,Cor,Ano,Valor_de_compra,Valor_de_Venda from veiculosWhere Ano<2010order by Ano/*10*/select count(Placa) from veiculos
where Ano>=2011 and Ano<=2016/*11*/select Placa,Marca,Modelo,Cor,Ano,Valor_de_compra,Valor_de_Venda from veiculosWhere Valor_de_Compra>=50000 and Valor_de_Compra<=65000/*12*/select Placa,Marca,Modelo,Cor,Ano,Valor_de_compra,Valor_de_Venda from veiculosWhere Marca='VOLKS' and Valor_de_Venda>30000 and Ano>=2013 and Ano<=2020/*13*/select Placa,Marca,Modelo,Cor,Ano,Valor_de_compra,Valor_de_Venda from veiculosWhere Marca='FORD' and Ano=2022 order by Modelo